# Define trigger for pipeline, e.g., on commits to the master branch
trigger:
- master

# Select the build agent (e.g., Ubuntu for Node.js)
pool:
  vmImage: 'ubuntu-latest'

# Define pipeline steps
steps:
# 1. Checkout the code from the repository
- checkout: self

# 2. Set up Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version
  displayName: 'Install Node.js'

# 3. Install npm dependencies
- script: npm install
  displayName: 'Install dependencies'

# 4. Run tests (optional)
- script: npm test
  displayName: 'Run tests'

# 5. Build the React application
- script: npm run build
  displayName: 'Build React app'

# 6. (Optional) Publish build artifacts
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'build'  # Specify the build output directory
    artifactName: 'react-build'
    publishLocation: 'pipeline'
  displayName: 'Publish Build Artifacts'
